Pull Request
kasisaki/go_task_tracker_final pull request #1
Opened 2024-05-03 02:08 UTC by kasisaki

To test if all work fine

2024-05-03 02:13 UTC, kasisaki commented
Все работает и с Веб интерфейсом, и через Postman, однако присутствует однотипная ошибка в трех наборах:
json: cannot unmarshal string into Go value of type map[string]interface {}
        	Test:       	TestEditTask
json: cannot unmarshal string into Go value of type map[string]interface {}
        	Test:       	TestDone
json: cannot unmarshal string into Go value of type map[string]interface {}
        	Test:       	TestDelTask
        	
Т.к. это напрямую ТЗ не связано - отправляю на проверку. Если скажете, что это критично - пойду искать причину. Пока не нашел.

2024-05-03 13:45 UTC, robotomize requested changes
В целом проект работает, я бы конечно сильно занялся бы рефакторингом в тех местах, что прокомментил, но по большому счету нужно поправить только вещи, где я написал крит, их совсем чуть чуть. К остальным можете вернуться самостоятельно

2024-05-03 13:45 UTC, robotomize commented on constants/constants.go
> +const (
Константы лучше держать ближе к месту использования. Например, если константа связана с пакетом x то лучше ее там и держать

2024-05-03 13:45 UTC, robotomize commented on constants/constants.go
> +const (
Например, все что связано с инициализацией db в пакете db, а стандартный порт прямо в main или где используется

2024-05-03 13:45 UTC, robotomize commented on db/dbSetup.go
> +package db
Нейминг db_setup.go но лучше просто setup так как мы уже находимся в пакете db. Нейминг нужно поправить, крит

2024-05-03 13:45 UTC, robotomize commented on db/put_task.go
> +func PutTask(task models.TaskDTO) error {
В Go не очень принято разбивать каждый метод на отдельны файл, нужно группировать по семантике. 
Второй момент, намного проще вам было бы создать структуру, скажем Store в которую проросить ваш глобальный DB при старте и инкапсулировать методы в рамках структуры, которую потом еще можно передавать в сервисы или хэндлеры либо явно, либо создав интерфейс

2024-05-03 13:45 UTC, robotomize commented on db/put_task.go
> +		fmt.Println(err)
Старайтесь логировать на самом высоком уровне, на уровне main или в хэндлерах

2024-05-03 13:45 UTC, robotomize commented on handlers/delete_task_handler.go
> +func HandleDeleteTask(w http.ResponseWriter, req *http.Request) {
Нейминг, приписывать хэндлер необязательно, мы и так в пакете хэндлер. Потом опять же разбивать по операциям может быть избыточно, но тут сами смотрите

2024-05-03 13:45 UTC, robotomize commented on handlers/get_tasks_handler.go
> +			utils.HandleError(w, 404, err)
Тут могут быть и другие ошибки. Во первых если мы проверяем на отсутствие записи в БД наверное лучше првоерить конкретно эту ошибку if errors.Is(err, sql.ErrNoRows) {} и если она есть, то тогда 404, если нет то нужно отдать InternalServerErrror. Это крит

2024-05-03 13:45 UTC, robotomize commented on handlers/delete_task_handler.go
> +	_, err = db.GetTaskById(id)
Думаю, что при удалении нам необзяательно проверять запись. БД просто ничего не сделает если записи нет, тем самым нам необязательно отдавать что-то говорить пользователю.

В вашем случае вы отдаете BadRequest, что не критично, но мне кажется может запутать его так как данные вроде как валидные, это скорее на будущее

2024-05-03 13:45 UTC, robotomize commented on schema.sql
> +CREATE INDEX IF NOT EXISTS idx_date ON scheduler(date);
Отлично, что добавили индекс!

2024-05-03 13:45 UTC, robotomize commented on services/next_date.go
> +	case "d":
Это очень большой метод, который сложно прочитать за раз. Желательно разбивать такой код, на несколько функций, которые вызывать в вашем switch case например

2024-05-03 13:45 UTC, robotomize commented on services/next_date.go
> +				// return time.Date(y, month, day, 0, 0, 0, 0, t.Location())
Мертвый код нужно убирать, закомменченный

2024-05-03 22:03 UTC, kasisaki commented
Исправил все критические замечания, и большую часть остальных. Спасибо за ревью

2024-05-04 11:07 UTC, robotomize approved these changes
Да, отлично, принято!

2024-05-30 13:06 UTC, merged